# Generated by Django 5.1 on 2024-09-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_encryptionkey_decryptionkey"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DecryptionKey",
        ),
    ]
